name: Build and Push ARM64 Docker Image of MiroTalk P2P

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      manual_build:
        description: 'Trigger manual build'
        required: false

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: miroslavpejic85/mirotalk

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push ARM64 image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: amadr/mirotalk-p2p-arm64:latest
